name: Deploy master branch

on:
  push:
    branches:
      - main
      - gitworkflow/kosha
      - gitworkflow/raveen

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
        
    steps:
    - name: Check out the repository to the runner
      uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.10'
    - name: Use python
      uses: actions/python@v4
      with:
        python-version: '3.6'
        cache: 'pip'
    - name: Build frontend component
      working-directory: ./frontend
      run: |
        npm ci
        npm run build
    - name: Install serverless npm packages
      run: npm ci
    - name: serverless deploy
      uses: serverless/github-action@v3.2
      with:
        args: deploy
      env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
